In [4]:
ls=[5,3,7,8,1,2,7,9]
i=0
j=len(ls)-1
while(i<j):
    temp=ls[i]
    ls[i]=ls[j]
    ls[j]=temp
    i+=1
    j-=1
print(ls)

[9, 7, 2, 1, 8, 7, 3, 5]


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [22]:
arr1=np.array([[1,2,6],[2,5,8]])
arr2=np.array([[2,3,5],[4,6,9]])
arr2=np.transpose(arr2)
print(arr1)
print(arr2)
# print(np.multiply(arr1,arr2))
print(np.dot(arr1,arr2))

[[1 2 6]
 [2 5 8]]
[[2 4]
 [3 6]
 [5 9]]
[[ 38  70]
 [ 59 110]]


In [27]:
x=np.arange(0,1,0.1)
y=np.sin(x)
print(y)
print(x)

[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
